### ISSUE TITLE
Warning: lite-image(...): React component classes must extend React.Component.

### ISSUE THREAD

**Issue by killfish** [jianliaoim/react-lite-image#3]
I'm not really familiar with CoffeeScript but this looks like it should work in normal JSX.

`<LiteImage src={this.state.image} height={100} width={100} />`

But I get the following error in my console: 

`Warning: lite-image(...): React component classes must extend React.Component.`

**Comment by tiye** [comment]
Is this new behavior in React 0.14.x ? I haven't tested it yet on 0.14.x ..
The component itself is created with `React.createClass`.

**Comment by tiye** [comment]
I think I've found the problem as I noticed similar issue in another project. It's because there are two copies of React when `0.14.x` is used and my components is writing `^0.13.3`.

For now just remove the nested `react` dependency and the warning will be gone. I need to update all our `package.json` files later. So many package affected...

**Comment by tiye** [comment]
Now it should work with `0.14.x`. Please check.

**Comment by killfish** [comment]
That works. Thank you!
